version: '3.8'

services:
  graphdb:
    build:
      context: ./GraphDB
      dockerfile: ./Dockerfile
    ports:
      - "7200:7200"
    volumes:
      - data:/opt/graphdb/home  # Persist data between container restarts

  sindit:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - environment_and_configuration/docker_environment_backend.env  # Load environment variables from this file
    depends_on:
      - graphdb
    ports:
      - "9017:9017"
volumes:
  data:
