version: '3.8'

services:
  graphdb:
    build:
      context: ./GraphDB
      dockerfile: ./Dockerfile
    ports:
      - "7200:7200"
    volumes:
      - data_graphdb:/opt/graphdb/home  # Persist data between container restarts

  sindit:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - src/sindit/environment_and_configuration/docker_environment_backend.env  # Load environment variables from this file
    depends_on:
      - graphdb
    ports:
      - "9017:9017"
    volumes:
      - ./data_sindit:/app/data  # Persist workspace and vault data to local folder

  postgres_keycloak:
    image: postgres:17
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
    volumes:
      - data_postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:  # ADD THIS
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5
  keycloak:
    build: ./keycloak
    depends_on:
      postgres_keycloak:
        condition: service_healthy  # ADD THIS - Wait for PostgreSQL to be healthy
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      KC_HOSTNAME: localhost
      KC_BOOTSTRAP_ADMIN_USERNAME: sindit
      KC_BOOTSTRAP_ADMIN_PASSWORD: sindit123
    ports:
      - "8443:8443"
      - "9000:9000"
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres_keycloak
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  data_graphdb:
  data_postgres:
  pgadmin_data:
