version: '3.8'

services:
  graphdb:
    build:
      context: ./GraphDB
      dockerfile: ./Dockerfile
    ports:
      - "7200:7200"

  sindit:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - GRAPHDB_HOST=graphdb
      - GRAPHDB_PORT=7200
    depends_on:
      - graphdb
    ports:
      - "9017:9017"
